git add ./*.py
git add ./*.sh
git add ./Slice/*
git add ./Net/BaseNet/LeNet/*.py
git add ./Net/MyNet/*.py
git add ./Net/MyNet/MultiScaleNet/*.py
git add ./Net/Test/*.py
git add ./Net/*.py
git add ./Slice/New_Max_Slice/*.py
git add ./Slice/New_Max_Slice/Using_BG/*.py
git add ./Net/MyNet/BG_LeNet/*.py
git add ./Net/MyNet/RNN_MultiScale/*.py
git add ./Net/MyNet/BG_RNN_MultiScale/*.py
git add ./Slice/TwoFolderMaxSlice/*.py
git add ./Patch/*.py
git add ./Net/BaseNet/VGG16/*.py
git add ./Net/BaseNet/LeNet_3/*.py
git add ./Net/BaseNet/ResNet/*.py